blur_ksize: '3'
brightness_adjust_on: true
brightness_factor: '1'
color_adjust_on: true
color_factor: '1.0'
dpi: '72'
gaussian_blur_on: false
horizontal_limit: '10'
jpeg_quality: '95'
link_vertical_horizontal: true
max_tile_usage: '5'
num_title: '10'
original_image_path: None
repeat_limit: '2'
resize_base_px: '5000'
rgb_values_file: output/rgb_values.txt
sub_blocks: '10'
tile_images_folder: None
vertical_limit: '10'
